import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import AppWrapper from "@/components/AppWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Valter 2025",
  description: "Generated by create next app",
  keywords: [
    "valter",
    "event polsri",
    "lomba web design",
    "lomba web developer",
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} relative bg-gray-950  antialiased`}
      >
        <div className="relative">
          <AppWrapper>{children}</AppWrapper>
        </div>
      </body>
    </html>
  );
}
